### ISSUE TITLE
Issue in point cloud upload

### ISSUE THREAD

**Issue by Soumya-V-S** [hasanari/sane#7]
Hi,
  I tried sane annotation tool in my Ubuntu 18.04 system. There is no GPU. After running python app.py on the terminal, opened the browser, selected the pcd file, but point cloud is not uploaded. On closing the terminal only the point cloud is uploaded in the browser. For annotating next frame, again python app.py is ran on the terminal, opened the browser, selected the frame, closed the terminal and point cloud is uploaded. Why it is so?

**Comment by hasanari** [comment]
Hi,

the list of pcd files is populated during startup (when you run python app.py). If more files were added after startup, it will not be included in the list. You have to rerun the app.py and reopen the browser to make sure the new files are also populated.

FYI, the codebase was taken from https://github.com/bernwang/latte/

**Comment by Karthikeyanc2** [comment]
Hi,
I am also facing the same problem. How did you fix ?
